spring:
datasource:
url: jdbc:postgresql://localhost:5432/student
username: postgres
password: 12344321
jpa:
    hibernate:
ddl-auto: create-drop
show-sql: true
properties:
    hibernate:
dialect : org.hibernate.dialect.PostgresSQLDialect
format_sql : true
